FileVersion = 1

[Project]
Name = "KeraLua"
TargetType = "BeefLib"
StartupObject = "KeraLua.Program"
ProcessorMacros = ["KERALUA_STATIC"]

[Configs.Debug.Win32]
LibPaths = ["$(ProjectDir)\\lib\\x86\\lua54.lib"]

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\lib\\x64\\lua54.lib"]

[Configs.Debug.Linux64]
LibPaths = ["$(ProjectDir)\\lib\\x64\\liblua54_static.a"]

[Configs.Debug.Linux32]
LibPaths = ["$(ProjectDir)\\lib\\x86\\liblua54_static.a"]

[Configs.Release.Win32]
LibPaths = ["$(ProjectDir)\\lib\\x64\\lua54.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\lib\\x64\\lua54.lib"]
